on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrmarch13.azurecr.io
        username: ${{ secrets.acr_acrmarch13_username }}
        password: ${{ secrets.acr_acrmarch13_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrmarch13.azurecr.io/k8smarch13:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrmarch13.azurecr.io/k8smarch13:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8smarch13_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep march13-nspace | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace march13-nspace`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: march13-nspace
        container-registry-url: acrmarch13.azurecr.io
        container-registry-username: ${{ secrets.acr_acrmarch13_username }}
        container-registry-password: ${{ secrets.acr_acrmarch13_password }}
        secret-name: k8smarch13dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: march13-nspace
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acrmarch13.azurecr.io/k8smarch13:${{ github.sha }}
        imagepullsecrets: |
          k8smarch13dockerauth
